version: '3'

services:

  php:
    build: ./
    volumes:
      - ./:/var/www/html
    ports:
      - 8089:80
    working_dir: /var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: test
      MYSQL_USER: root
    volumes:
      - ./databases:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 6089:8080

  composer:
    image: composer:1.7
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: composer install